### ISSUE TITLE
Where to find bold words

### ISSUE THREAD

**Issue by mascardoso** [ysjn/bold-it#7]
Hi @ysjn .
Maybe not the proper place to ask this. But I bumped into your code and tried to look for it but couldn't.
I'm also doing a plugin where I would also like to understand if a text layer has a regular font weight but it contains a word in bold. How can I know that? 

So for instance the following text layer:
lorem ipsum lorem ipsum **bold-word** ipsum

How can I find in the text layer that it is completely regular that contains a word in bold?

Hope you can help me out.
Thanks.

**Comment by ysjn** [comment]
Hi @mascardoso, sorry for my late reply.

**Please note that I'm new to cocoa-script and Objective-c, Sketch plugin authoring** :wink:

I did some quick search and came to conclusion that maybe you can use `attributedStringValue()` from Objective-c.

```js
import sketch from 'sketch'

export default function() {
  const selection = context.selection;

  for (var index = selection.length - 1; index >= 0; index--) {
    var layer = selection[index];
    console.log(layer.attributedStringValue().string);
  }
}
```

From the code above, you can retrieve an object that contains all paragraph styles from text layer(s).
If I run that code against text layer that contains something like, 

"Type **something**"

I would get:
```objectiveC
<MOMethod: 0x600000c25860 : target=0x608001227c00
Type {
    MSAttributedStringColorAttribute = "<MSImmutableColor: 0x600000c66800> (C10CE689-E370-4BBC-9EE8-B4BE54858E53)";
    NSFont = "\"ArialMT 13.00 pt. P [] (0x600001258d80) fobj=0x7fbb1973f100, spc=3.61\"";
    NSParagraphStyle = "Alignment 0, LineSpacing 0, ParagraphSpacing 0, ParagraphSpacingBefore 0, HeadIndent 0, TailIndent 0, FirstLineHeadIndent 0, LineHeight 0/0, LineHeightMultiple 0, LineBreakMode 0, Tabs (\n    28L,\n    56L,\n    84L,\n    112L,\n    140L,\n    168L,\n    196L,\n    224L,\n    252L,\n    280L,\n    308L,\n    336L\n), DefaultTabInterval 0, Blocks (\n), Lists (\n), BaseWritingDirection -1, HyphenationFactor 0, TighteningForTruncation NO, HeaderLevel 0";
    textStyleVerticalAlignmentKey = 0;
}
something{
    MSAttributedStringColorAttribute = "<MSImmutableColor: 0x600000c66800> (C10CE689-E370-4BBC-9EE8-B4BE54858E53)";
    NSFont = "\"Arial-BoldMT 13.00 pt. P [] (0x604000c46840) fobj=0x7fbb0e18fad0, spc=3.61\"";
    NSParagraphStyle = "Alignment 0, LineSpacing 0, ParagraphSpacing 0, ParagraphSpacingBefore 0, HeadIndent 0, TailIndent 0, FirstLineHeadIndent 0, LineHeight 0/0, LineHeightMultiple 0, LineBreakMode 0, Tabs (\n    28L,\n    56L,\n    84L,\n    112L,\n    140L,\n    168L,\n    196L,\n    224L,\n    252L,\n    280L,\n    308L,\n    336L\n), DefaultTabInterval 0, Blocks (\n), Lists (\n), BaseWritingDirection -1, HyphenationFactor 0, TighteningForTruncation NO, HeaderLevel 0";
    textStyleVerticalAlignmentKey = 0;
}, 
selector=string>
```
Pay attention to `NSFont = "\"ArialMT...` and `NSFont = "\"Arial-BoldMT...`.

From that object you can find NSFont that contains bold weight of selected text layer.
Note that you have to find which weight is the bold weight for the font though.

Maybe you can do something similar to what I'm doing in my plugin [here](https://github.com/ysjn/bold-it/blob/dev/src/main.js#L26).

```js
NSFontManager.sharedFontManager().convertFont_toHaveTrait(layer.font(), 2);
```
> * `layer` is currently selected layer.
> * If you make font object to have trait of value "2", it seems that is the predefined bold font.
> @see: https://developer.apple.com/documentation/appkit/nsfontmanager/1462345-convertfont

You can compare the paragraph style retrieved earlier to the bold font attribute you retrieved from code right above.

Hope this helps.
Cheers.

**Comment by mascardoso** [comment]
@ysjn this definitely helps to get me through a direction.
Thank you so much with the thorough explanation.
I will let you know about my findings soon.
Thank you

**Comment by ysjn** [comment]
Great! I'm closing this issue but feel free to reopen if you need.
Looking forward to hearing your findings, good luck! 👍
